import { KeyCode } from '@lvce-editor/virtual-dom-worker'
import * as KeyCodeString from '../KeyCodeString/KeyCodeString.ts'

const keyCodeStrings: Record<number, string> = {
  [KeyCode.Backquote]: KeyCodeString.Backquote,
  [KeyCode.Backslash]: KeyCodeString.Backslash,
  [KeyCode.Backspace]: KeyCodeString.Backspace,
  [KeyCode.Comma]: KeyCodeString.Comma,
  [KeyCode.Delete]: KeyCodeString.Delete,
  [KeyCode.Digit0]: KeyCodeString.Digit0,
  [KeyCode.Digit1]: KeyCodeString.Digit1,
  [KeyCode.Digit2]: KeyCodeString.Digit2,
  [KeyCode.Digit3]: KeyCodeString.Digit3,
  [KeyCode.Digit4]: KeyCodeString.Digit4,
  [KeyCode.Digit5]: KeyCodeString.Digit5,
  [KeyCode.Digit6]: KeyCodeString.Digit6,
  [KeyCode.Digit7]: KeyCodeString.Digit7,
  [KeyCode.Digit8]: KeyCodeString.Digit8,
  [KeyCode.Digit9]: KeyCodeString.Digit9,
  [KeyCode.DownArrow]: KeyCodeString.DownArrow,
  [KeyCode.End]: KeyCodeString.End,
  [KeyCode.Enter]: KeyCodeString.Enter,
  [KeyCode.Equal]: KeyCodeString.Equal,
  [KeyCode.Escape]: KeyCodeString.Escape,
  [KeyCode.F1]: KeyCodeString.F1,
  [KeyCode.F2]: KeyCodeString.F2,
  [KeyCode.F3]: KeyCodeString.F3,
  [KeyCode.F4]: KeyCodeString.F4,
  [KeyCode.F5]: KeyCodeString.F5,
  [KeyCode.F6]: KeyCodeString.F6,
  [KeyCode.Home]: KeyCodeString.Home,
  [KeyCode.Insert]: KeyCodeString.Insert,
  [KeyCode.KeyA]: KeyCodeString.KeyA,
  [KeyCode.KeyB]: KeyCodeString.KeyB,
  [KeyCode.KeyC]: KeyCodeString.KeyC,
  [KeyCode.KeyD]: KeyCodeString.KeyD,
  [KeyCode.KeyE]: KeyCodeString.KeyE,
  [KeyCode.KeyF]: KeyCodeString.KeyF,
  [KeyCode.KeyG]: KeyCodeString.KeyG,
  [KeyCode.KeyH]: KeyCodeString.KeyH,
  [KeyCode.KeyI]: KeyCodeString.KeyI,
  [KeyCode.KeyJ]: KeyCodeString.KeyJ,
  [KeyCode.KeyK]: KeyCodeString.KeyK,
  [KeyCode.KeyL]: KeyCodeString.KeyL,
  [KeyCode.KeyM]: KeyCodeString.KeyM,
  [KeyCode.KeyN]: KeyCodeString.KeyN,
  [KeyCode.KeyO]: KeyCodeString.KeyO,
  [KeyCode.KeyP]: KeyCodeString.KeyP,
  [KeyCode.KeyQ]: KeyCodeString.KeyQ,
  [KeyCode.KeyR]: KeyCodeString.KeyR,
  [KeyCode.KeyS]: KeyCodeString.KeyS,
  [KeyCode.KeyT]: KeyCodeString.KeyT,
  [KeyCode.KeyU]: KeyCodeString.KeyU,
  [KeyCode.KeyV]: KeyCodeString.KeyV,
  [KeyCode.KeyW]: KeyCodeString.KeyW,
  [KeyCode.KeyX]: KeyCodeString.KeyX,
  [KeyCode.KeyY]: KeyCodeString.KeyY,
  [KeyCode.KeyZ]: KeyCodeString.KeyZ,
  [KeyCode.LeftArrow]: KeyCodeString.LeftArrow,
  [KeyCode.Minus]: KeyCodeString.Minus,
  [KeyCode.PageDown]: KeyCodeString.PageDown,
  [KeyCode.PageUp]: KeyCodeString.PageUp,
  [KeyCode.Plus]: KeyCodeString.Plus,
  [KeyCode.RightArrow]: KeyCodeString.RightArrow,
  [KeyCode.Space]: KeyCodeString.Space,
  [KeyCode.Star]: KeyCodeString.Star,
  [KeyCode.Tab]: KeyCodeString.Tab,
  [KeyCode.UpArrow]: KeyCodeString.UpArrow,
}

export const getKeyCodeString = (keyCode: number): string => {
  return keyCodeStrings[keyCode] || KeyCodeString.Unknown
}
