import type { KeyBindingsState } from '../KeyBindingsState/KeyBindingsState.ts'
import * as InputSource from '../InputSource/InputSource.ts'

export const createDefaultState = (): KeyBindingsState => {
  return {
    columnWidth0: 30,
    columnWidth1: 0,
    columnWidth2: 0,
    columnWidth3: 0,
    contentPadding: 30,
    defineKeyBindingsId: -1,
    deltaY: 0,
    editIconSize: 22,
    editingWhenExpression: false,
    finalDeltaY: 0,
    focus: 0,
    focusedIndex: -1,
    headerHeight: 0,
    height: 100,
    initial: false,
    inputSource: InputSource.User,
    isRecordingKeys: false,
    isSortingByPrecedence: false,
    itemHeight: 24,
    items: [],
    maxLineY: 0,
    maxVisibleItems: 0,
    minimumSliderSize: 20,
    minLineY: 0,
    padding: 15,
    paddingLeft: 27,
    parsedKeyBindings: [],
    placeholder: '',
    recordingKeysLabelWidth: 0,
    resizerDownId: 0,
    resizerOneLeft: 0,
    resizerTwoLeft: 0,
    searchHeaderHeight: 50,
    selectedIndex: -1,
    tableHeaderHeight: 24,
    uid: 1,
    uri: '',
    value: '',
    visibleItems: [],
    whenExpressionText: '',
    width: 100,
    x: 0,
    y: 0,
  }
}
